// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("zh-CN")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"凭证生成失败": 0,
	"成功":     1,
}

var en_USIndex = []uint32{ // 3 elements
	0x00000000, 0x0000001d, 0x00000025,
} // Size: 36 bytes

const en_USData string = "\x02Credential generation failed\x02success"

var zh_CNIndex = []uint32{ // 3 elements
	0x00000000, 0x00000013, 0x0000001a,
} // Size: 36 bytes

const zh_CNData string = "\x02凭证生成失败\x02成功"

// Total table size 135 bytes (0KiB); checksum: F08795AF
